

public enum GameState {
    SETUP_BOARD,
    START_TURN,
    TURN_STARTED,
    BUILD_CITY,
    BUILD_ROAD,
    BUILD_SETTLEMENT,
    TRADE_PLAYER,
    TRADE_BANK,
    PLACE_ROBBER,
    PAY_7_TAX,
    CHOOSE_VICTIM,
    PLAY_KNIGHT,
    PLAY_YEAR_OF_PLENTY,
    PLAY_VICTORY_POINT,
    PLAY_MONOPOLY,
    PLAY_ROAD_BUILDER,
    GAME_WON
}
